# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech-ts.o
focaltech-ts-y += focaltech_core.o
focaltech-ts-y += focaltech_i2c.o


